-- MySQL Script generated by MySQL Workbench
-- Mon Aug  5 10:51:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema payment_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payment_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payment_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `payment_management` ;

-- -----------------------------------------------------
-- Table `payment_management`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_management`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payment_management`.`payment_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_management`.`payment_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `card_number` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `expiry_date` VARCHAR(20) NOT NULL,
  `account_name` VARCHAR(20) NULL DEFAULT NULL,
  `status` ENUM('99', '200', '201') NOT NULL DEFAULT '99',
  `last_name` VARCHAR(100) NOT NULL,
  `cvv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `payment_requests_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `payment_management`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
